---
- hosts: webservers
  vars:
     appname: CTR DEVCUL
     tiername: CTR CUI
     nodename: "{{ ansible_nodename.split('.')[0] }}"
  tasks:
    - block:
        - name: Install appdynamics.
          remote_user: ansible 
          synchronize:  
            src: /home/ansible/AppDynamics4.1.4.0/ 
            dest: /opt/AppDynamics4.1.4.0 recursive=yes
          delegate_to: 10.2.0.30

        - name: Setup Startup Script
          synchronize:  src=/home/ansible/appdynamics dest=/etc/init.d/

        - name: Creating SymLink for the folder
          file: path=/opt/AppDynamics src=/opt/AppDynamics4.1.4.0/ state=link force=yes

        - name: Copy and create config
          template:
            src: /home/ansible/AppDynamics4.1.4.0/MachineAgent-4.1.4.0/conf/controller-info.xml.j2
            dest: /opt/AppDynamics4.1.4.0/MachineAgent-4.1.4.0/conf/controller-info.xml
            mode: 0644

        - name: Starting Appdynamics Machine Agent
          service: name=appdynamics state=started enabled=yes
    
      when: ansible_nodename.split('.')[1]=='dev'
      sudo: yes
